In [ ]:
# Tensorflow > 2.0 and Keras

In [1]:
# Tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
# Vocabulary Size
voc_size = 10000

### One Hot Representation

In [10]:
onehot_repr = [one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[8405, 834, 9833, 872], [8405, 834, 9833, 5907], [8405, 2277, 9833, 5923], [6733, 9390, 37, 6900, 6153], [6733, 9390, 37, 6900, 7899], [5346, 8405, 7692, 9833, 9812], [8481, 2868, 540, 6900]]


### Word Embedding Representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8405  834 9833  872]
 [   0    0    0    0 8405  834 9833 5907]
 [   0    0    0    0 8405 2277 9833 5923]
 [   0    0    0 6733 9390   37 6900 6153]
 [   0    0    0 6733 9390   37 6900 7899]
 [   0    0    0 5346 8405 7692 9833 9812]
 [   0    0    0    0 8481 2868  540 6900]]


In [14]:
dim = 10

In [16]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

[[[-9.7761154e-03 -1.8419754e-02 -4.1602232e-02  3.1799559e-02
   -3.9661087e-02  7.4461810e-03 -3.9770700e-02  6.1346516e-03
   -7.7999607e-03  2.9977228e-02]
  [-9.7761154e-03 -1.8419754e-02 -4.1602232e-02  3.1799559e-02
   -3.9661087e-02  7.4461810e-03 -3.9770700e-02  6.1346516e-03
   -7.7999607e-03  2.9977228e-02]
  [-9.7761154e-03 -1.8419754e-02 -4.1602232e-02  3.1799559e-02
   -3.9661087e-02  7.4461810e-03 -3.9770700e-02  6.1346516e-03
   -7.7999607e-03  2.9977228e-02]
  [-9.7761154e-03 -1.8419754e-02 -4.1602232e-02  3.1799559e-02
   -3.9661087e-02  7.4461810e-03 -3.9770700e-02  6.1346516e-03
   -7.7999607e-03  2.9977228e-02]
  [ 4.7218274e-02  2.4346020e-02 -1.8576026e-02  3.5298411e-02
   -2.4781395e-02 -1.8261790e-02 -1.1901140e-02 -1.3237834e-02
    1.0506995e-03  2.6320528e-02]
  [-2.8236926e-02  1.4682021e-02 -1.5564181e-02  1.9608811e-04
   -2.3100153e-03  2.8791402e-02  2.2717003e-02 -2.4808753e-02
   -1.2288950e-02  2.4800289e-02]
  [ 3.0382071e-02 -3.9364170e-02 -2.4575

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 8405,  834, 9833,  872])

In [20]:
print(model.predict(embedded_docs)[0])

[[-0.00977612 -0.01841975 -0.04160223  0.03179956 -0.03966109  0.00744618
  -0.0397707   0.00613465 -0.00779996  0.02997723]
 [-0.00977612 -0.01841975 -0.04160223  0.03179956 -0.03966109  0.00744618
  -0.0397707   0.00613465 -0.00779996  0.02997723]
 [-0.00977612 -0.01841975 -0.04160223  0.03179956 -0.03966109  0.00744618
  -0.0397707   0.00613465 -0.00779996  0.02997723]
 [-0.00977612 -0.01841975 -0.04160223  0.03179956 -0.03966109  0.00744618
  -0.0397707   0.00613465 -0.00779996  0.02997723]
 [ 0.04721827  0.02434602 -0.01857603  0.03529841 -0.02478139 -0.01826179
  -0.01190114 -0.01323783  0.0010507   0.02632053]
 [-0.02823693  0.01468202 -0.01556418  0.00019609 -0.00231002  0.0287914
   0.022717   -0.02480875 -0.01228895  0.02480029]
 [ 0.03038207 -0.03936417 -0.02457585  0.00010865  0.01505532 -0.02475158
  -0.02440019  0.02901253  0.00893684  0.0471676 ]
 [ 0.00075306 -0.04645297  0.0378427   0.02634379 -0.02889856 -0.04500509
  -0.03726751 -0.00991011 -0.03206849 -0.0191588 ]]
